### ISSUE TITLE
Cloudinary Incompatible with Image Picker

### ISSUE THREAD

**Issue by fjnoyp** [luis901101/cloudinary-sdk#4]
Hi guys would love to use Cloudinary in Flutter but it's not compatible with the basic Image Picker dependency. 

Here is my pubspec: 

```
dependencies:
  flutter:
    sdk: flutter

  image_picker: ^0.8.4+5
  cloudinary_sdk: ^1.0.0+1
```

But I get this error: 

> Because cloudinary_sdk <3.0.0+6 depends on dio ^3.0.10 and no versions of dio match >3.0.10 <4.0.0, cloudinary_sdk <3.0.0+6 requires dio 3.0.10.
> And because dio 3.0.10 depends on http_parser >=0.0.1 <4.0.0 and http >=0.13.0 depends on http_parser ^4.0.0, cloudinary_sdk <3.0.0+6 is incompatible with http >=0.13.0.
> So, because wingman depends on both cloudinary_sdk ^1.0.0+1 and http ^0.13.0, version solving failed.
> pub get failed (1; So, because wingman depends on both cloudinary_sdk ^1.0.0+1 and http ^0.13.0, version solving failed.)
